DO $$
BEGIN
	IF NOT EXISTS (
		SELECT 1
		FROM pg_class c
		JOIN pg_namespace n ON n.oid = c.relnamespace
		WHERE c.relname = 't3-app-template_user'
		AND n.nspname = current_schema()
		AND c.relkind = 'r'
	) THEN
		CREATE TABLE "t3-app-template_user" (
			"id" integer PRIMARY KEY,
			"username" varchar(50) NOT NULL,
			"email" varchar(255) NOT NULL,
			"passwordHash" varchar(255) NOT NULL,
			"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
			"updatedAt" timestamp with time zone
		);

		IF EXISTS (
			SELECT 1
			FROM pg_class c
			JOIN pg_namespace n ON n.oid = c.relnamespace
			WHERE c.relname = 't3-app-template_user_id_seq'
			AND n.nspname = current_schema()
			AND c.relkind = 'S'
		) THEN
			ALTER SEQUENCE "t3-app-template_user_id_seq" OWNED BY "t3-app-template_user"."id";
			ALTER TABLE "t3-app-template_user" ALTER COLUMN "id" SET DEFAULT nextval('"t3-app-template_user_id_seq"'::regclass);
		ELSE
			ALTER TABLE "t3-app-template_user"
				ALTER COLUMN "id"
				ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "t3-app-template_user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);
		END IF;
	END IF;
END $$;
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "user_username_unique" ON "t3-app-template_user" USING btree ("username");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "user_email_unique" ON "t3-app-template_user" USING btree ("email");
