CREATE TABLE "t3-app-template_user" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "t3-app-template_user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"username" varchar(50) NOT NULL,
	"email" varchar(255) NOT NULL,
	"passwordHash" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE UNIQUE INDEX "user_username_unique" ON "t3-app-template_user" USING btree ("username");--> statement-breakpoint
CREATE UNIQUE INDEX "user_email_unique" ON "t3-app-template_user" USING btree ("email");