-- Calendar core schema
-- Adds displayName to user
ALTER TABLE "t3-app-template_user" ADD COLUMN IF NOT EXISTS "displayName" varchar(255) DEFAULT '' NOT NULL;

-- Calendars
CREATE TABLE IF NOT EXISTS "t3-app-template_calendar" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "userId" integer NOT NULL,
  "name" varchar(100) NOT NULL,
  "color" varchar(32) DEFAULT '#22c55e' NOT NULL,
  "isPrimary" boolean DEFAULT false NOT NULL,
  "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updatedAt" timestamp with time zone
);
CREATE INDEX IF NOT EXISTS "calendar_user_idx" ON "t3-app-template_calendar" ("userId");
ALTER TABLE "t3-app-template_calendar"
  ADD CONSTRAINT "calendar_user_fk" FOREIGN KEY ("userId") REFERENCES "t3-app-template_user"("id") ON DELETE CASCADE;

-- Events
CREATE TABLE IF NOT EXISTS "t3-app-template_event" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "calendarId" integer NOT NULL,
  "title" varchar(255) NOT NULL,
  "description" text,
  "location" varchar(255),
  "isAllDay" boolean DEFAULT false NOT NULL,
  "startDatetime" timestamp with time zone NOT NULL,
  "endDatetime" timestamp with time zone NOT NULL,
  "recurrenceRule" text,
  "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updatedAt" timestamp with time zone
);
CREATE INDEX IF NOT EXISTS "event_calendar_idx" ON "t3-app-template_event" ("calendarId");
CREATE INDEX IF NOT EXISTS "event_start_idx" ON "t3-app-template_event" ("startDatetime");
ALTER TABLE "t3-app-template_event"
  ADD CONSTRAINT "event_calendar_fk" FOREIGN KEY ("calendarId") REFERENCES "t3-app-template_calendar"("id") ON DELETE CASCADE;

-- Event attendees
CREATE TABLE IF NOT EXISTS "t3-app-template_event_attendee" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "eventId" integer NOT NULL,
  "email" varchar(255) NOT NULL,
  "responseStatus" varchar(32) DEFAULT 'needsAction' NOT NULL
);
CREATE INDEX IF NOT EXISTS "attendee_event_idx" ON "t3-app-template_event_attendee" ("eventId");
ALTER TABLE "t3-app-template_event_attendee"
  ADD CONSTRAINT "attendee_event_fk" FOREIGN KEY ("eventId") REFERENCES "t3-app-template_event"("id") ON DELETE CASCADE;

-- Event reminders
CREATE TABLE IF NOT EXISTS "t3-app-template_event_reminder" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "eventId" integer NOT NULL,
  "reminderMinutes" integer DEFAULT 30 NOT NULL
);
CREATE INDEX IF NOT EXISTS "reminder_event_idx" ON "t3-app-template_event_reminder" ("eventId");
ALTER TABLE "t3-app-template_event_reminder"
  ADD CONSTRAINT "reminder_event_fk" FOREIGN KEY ("eventId") REFERENCES "t3-app-template_event"("id") ON DELETE CASCADE;

