DO $$
BEGIN
  CREATE TYPE "business_type" AS ENUM ('university', 'nonprofit', 'corporation', 'government', 'venue', 'other');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$
BEGIN
  CREATE TYPE "organization_role_type" AS ENUM ('admin', 'manager', 'employee');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$
BEGIN
  CREATE TYPE "organization_scope_type" AS ENUM ('business', 'department', 'division');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

CREATE TABLE IF NOT EXISTS "t3-app-template_business" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar(255) NOT NULL,
  "type" "business_type" DEFAULT 'other' NOT NULL,
  "setupCompletedAt" timestamptz,
  "createdAt" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updatedAt" timestamptz
);
CREATE UNIQUE INDEX IF NOT EXISTS "business_name_unique" ON "t3-app-template_business" ("name");

CREATE TABLE IF NOT EXISTS "t3-app-template_building" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "businessId" integer NOT NULL,
  "name" varchar(255) NOT NULL,
  "acronym" varchar(32) NOT NULL,
  "createdAt" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updatedAt" timestamptz
);
CREATE INDEX IF NOT EXISTS "building_business_idx" ON "t3-app-template_building" ("businessId");
CREATE UNIQUE INDEX IF NOT EXISTS "building_business_acronym_idx" ON "t3-app-template_building" ("businessId", "acronym");
ALTER TABLE "t3-app-template_building"
  ADD CONSTRAINT "building_business_fk"
  FOREIGN KEY ("businessId") REFERENCES "t3-app-template_business" ("id") ON DELETE CASCADE;

CREATE TABLE IF NOT EXISTS "t3-app-template_room" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "buildingId" integer NOT NULL,
  "roomNumber" varchar(64) NOT NULL,
  "createdAt" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updatedAt" timestamptz
);
CREATE INDEX IF NOT EXISTS "room_building_idx" ON "t3-app-template_room" ("buildingId");
CREATE UNIQUE INDEX IF NOT EXISTS "room_building_number_idx" ON "t3-app-template_room" ("buildingId", "roomNumber");
ALTER TABLE "t3-app-template_room"
  ADD CONSTRAINT "room_building_fk"
  FOREIGN KEY ("buildingId") REFERENCES "t3-app-template_building" ("id") ON DELETE CASCADE;

CREATE TABLE IF NOT EXISTS "t3-app-template_department" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "businessId" integer NOT NULL,
  "parentDepartmentId" integer,
  "name" varchar(255) NOT NULL,
  "createdAt" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updatedAt" timestamptz
);
CREATE INDEX IF NOT EXISTS "department_business_idx" ON "t3-app-template_department" ("businessId");
CREATE INDEX IF NOT EXISTS "department_parent_idx" ON "t3-app-template_department" ("parentDepartmentId");
ALTER TABLE "t3-app-template_department"
  ADD CONSTRAINT "department_business_fk"
  FOREIGN KEY ("businessId") REFERENCES "t3-app-template_business" ("id") ON DELETE CASCADE;
ALTER TABLE "t3-app-template_department"
  ADD CONSTRAINT "department_parent_fk"
  FOREIGN KEY ("parentDepartmentId") REFERENCES "t3-app-template_department" ("id") ON DELETE CASCADE;

CREATE TABLE IF NOT EXISTS "t3-app-template_organization_role" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "userId" integer NOT NULL,
  "profileId" integer NOT NULL,
  "roleType" "organization_role_type" NOT NULL,
  "scopeType" "organization_scope_type" NOT NULL,
  "scopeId" integer NOT NULL,
  "createdAt" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updatedAt" timestamptz
);
CREATE INDEX IF NOT EXISTS "organization_role_user_idx" ON "t3-app-template_organization_role" ("userId");
CREATE INDEX IF NOT EXISTS "organization_role_scope_idx" ON "t3-app-template_organization_role" ("scopeType", "scopeId");
CREATE UNIQUE INDEX IF NOT EXISTS "organization_role_unique" ON "t3-app-template_organization_role" ("userId", "scopeType", "scopeId", "roleType");
ALTER TABLE "t3-app-template_organization_role"
  ADD CONSTRAINT "organization_role_user_fk"
  FOREIGN KEY ("userId") REFERENCES "t3-app-template_user" ("id") ON DELETE CASCADE;
ALTER TABLE "t3-app-template_organization_role"
  ADD CONSTRAINT "organization_role_profile_fk"
  FOREIGN KEY ("profileId") REFERENCES "t3-app-template_profile" ("id") ON DELETE CASCADE;
