-- Event hour logging
CREATE TABLE IF NOT EXISTS "t3-app-template_event_hour_log" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "eventId" integer NOT NULL,
  "startTime" timestamp with time zone NOT NULL,
  "endTime" timestamp with time zone NOT NULL,
  "durationMinutes" integer NOT NULL,
  "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS "event_hour_log_event_idx" ON "t3-app-template_event_hour_log" ("eventId");

ALTER TABLE "t3-app-template_event_hour_log"
  ADD CONSTRAINT "event_hour_log_event_fk" FOREIGN KEY ("eventId") REFERENCES "t3-app-template_event"("id") ON DELETE CASCADE;
