DO $$
BEGIN
  CREATE TYPE "public"."business_type" AS ENUM('university', 'nonprofit', 'corporation', 'government', 'venue', 'other');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;--> statement-breakpoint
DO $$
BEGIN
  CREATE TYPE "public"."event_request_category" AS ENUM('university_affiliated_request_to_university_business', 'university_affiliated_nonrequest_to_university_business', 'fgcu_student_affiliated_event', 'non_affiliated_or_revenue_generating_event');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;--> statement-breakpoint
DO $$
BEGIN
  CREATE TYPE "public"."organization_role_type" AS ENUM('admin', 'manager', 'employee');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;--> statement-breakpoint
DO $$
BEGIN
  CREATE TYPE "public"."organization_scope_type" AS ENUM('business', 'department', 'division');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;--> statement-breakpoint
DO $$
BEGIN
  CREATE TYPE "public"."theme_profile_scope" AS ENUM('business', 'department');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "t3-app-template_building" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "t3-app-template_building_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"businessId" integer NOT NULL,
	"name" varchar(255) NOT NULL,
	"acronym" varchar(32) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "t3-app-template_business" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "t3-app-template_business_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"type" "business_type" DEFAULT 'other' NOT NULL,
	"setupCompletedAt" timestamp with time zone,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "t3-app-template_calendar" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "t3-app-template_calendar_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"name" varchar(100) NOT NULL,
	"color" varchar(32) DEFAULT '#22c55e' NOT NULL,
	"isPrimary" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "t3-app-template_department" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "t3-app-template_department_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"businessId" integer NOT NULL,
	"parentDepartmentId" integer,
	"name" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "t3-app-template_event_attendee" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "t3-app-template_event_attendee_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"eventId" integer NOT NULL,
	"profileId" integer,
	"email" varchar(255) NOT NULL,
	"responseStatus" varchar(32) DEFAULT 'needsAction' NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "t3-app-template_event_hour_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "t3-app-template_event_hour_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"eventId" integer NOT NULL,
	"loggedByProfileId" integer,
	"startTime" timestamp with time zone NOT NULL,
	"endTime" timestamp with time zone NOT NULL,
	"durationMinutes" integer NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "t3-app-template_event_reminder" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "t3-app-template_event_reminder_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"eventId" integer NOT NULL,
	"reminderMinutes" integer DEFAULT 30 NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "t3-app-template_event_zendesk_confirmation" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "t3-app-template_event_zendesk_confirmation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"eventId" integer NOT NULL,
	"profileId" integer NOT NULL,
	"confirmedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "t3-app-template_event" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "t3-app-template_event_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"calendarId" integer NOT NULL,
	"buildingId" integer,
	"assigneeProfileId" integer,
	"eventCode" varchar(7) NOT NULL,
	"title" varchar(255) NOT NULL,
	"description" text,
	"location" varchar(255),
	"isAllDay" boolean DEFAULT false NOT NULL,
	"startDatetime" timestamp with time zone NOT NULL,
	"endDatetime" timestamp with time zone NOT NULL,
	"recurrenceRule" text,
	"participantCount" integer,
	"technicianNeeded" boolean DEFAULT false NOT NULL,
	"requestCategory" "event_request_category",
	"equipmentNeeded" text,
	"eventStartTime" timestamp with time zone,
	"eventEndTime" timestamp with time zone,
	"setupTime" timestamp with time zone,
	"zendeskTicketNumber" varchar(64),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "t3-app-template_organization_role" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "t3-app-template_organization_role_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"profileId" integer NOT NULL,
	"roleType" "organization_role_type" NOT NULL,
	"scopeType" "organization_scope_type" NOT NULL,
	"scopeId" integer NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "t3-app-template_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "t3-app-template_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "t3-app-template_profile" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "t3-app-template_profile_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer,
	"firstName" varchar(100) NOT NULL,
	"lastName" varchar(100) NOT NULL,
	"email" varchar(255) NOT NULL,
	"phoneNumber" varchar(32) NOT NULL,
	"dateOfBirth" date,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "t3-app-template_room" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "t3-app-template_room_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"buildingId" integer NOT NULL,
	"roomNumber" varchar(64) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "t3-app-template_theme_palette" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "t3-app-template_theme_palette_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"businessId" integer NOT NULL,
	"name" varchar(120) NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"tokens" jsonb NOT NULL,
	"isDefault" boolean DEFAULT false NOT NULL,
	"createdByUserId" integer,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "t3-app-template_theme_profile" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "t3-app-template_theme_profile_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"businessId" integer NOT NULL,
	"scopeType" "theme_profile_scope" NOT NULL,
	"scopeId" integer NOT NULL,
	"label" varchar(120) DEFAULT '' NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"paletteId" integer NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "t3-app-template_user" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "t3-app-template_user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"username" varchar(50) NOT NULL,
	"email" varchar(255) NOT NULL,
	"displayName" varchar(255) DEFAULT '' NOT NULL,
	"passwordHash" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "t3-app-template_building" ADD CONSTRAINT "t3-app-template_building_businessId_t3-app-template_business_id_fk" FOREIGN KEY ("businessId") REFERENCES "public"."t3-app-template_business"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "t3-app-template_calendar" ADD CONSTRAINT "t3-app-template_calendar_userId_t3-app-template_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."t3-app-template_user"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "t3-app-template_department" ADD CONSTRAINT "t3-app-template_department_businessId_t3-app-template_business_id_fk" FOREIGN KEY ("businessId") REFERENCES "public"."t3-app-template_business"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "t3-app-template_department" ADD CONSTRAINT "department_parent_fk" FOREIGN KEY ("parentDepartmentId") REFERENCES "public"."t3-app-template_department"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "t3-app-template_event_attendee" ADD CONSTRAINT "t3-app-template_event_attendee_eventId_t3-app-template_event_id_fk" FOREIGN KEY ("eventId") REFERENCES "public"."t3-app-template_event"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "t3-app-template_event_attendee" ADD CONSTRAINT "t3-app-template_event_attendee_profileId_t3-app-template_profile_id_fk" FOREIGN KEY ("profileId") REFERENCES "public"."t3-app-template_profile"("id") ON DELETE set null ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "t3-app-template_event_hour_log" ADD CONSTRAINT "t3-app-template_event_hour_log_eventId_t3-app-template_event_id_fk" FOREIGN KEY ("eventId") REFERENCES "public"."t3-app-template_event"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "t3-app-template_event_hour_log" ADD CONSTRAINT "t3-app-template_event_hour_log_loggedByProfileId_t3-app-template_profile_id_fk" FOREIGN KEY ("loggedByProfileId") REFERENCES "public"."t3-app-template_profile"("id") ON DELETE set null ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "t3-app-template_event_reminder" ADD CONSTRAINT "t3-app-template_event_reminder_eventId_t3-app-template_event_id_fk" FOREIGN KEY ("eventId") REFERENCES "public"."t3-app-template_event"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "t3-app-template_event_zendesk_confirmation" ADD CONSTRAINT "t3-app-template_event_zendesk_confirmation_eventId_t3-app-template_event_id_fk" FOREIGN KEY ("eventId") REFERENCES "public"."t3-app-template_event"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "t3-app-template_event_zendesk_confirmation" ADD CONSTRAINT "t3-app-template_event_zendesk_confirmation_profileId_t3-app-template_profile_id_fk" FOREIGN KEY ("profileId") REFERENCES "public"."t3-app-template_profile"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "t3-app-template_event" ADD CONSTRAINT "t3-app-template_event_calendarId_t3-app-template_calendar_id_fk" FOREIGN KEY ("calendarId") REFERENCES "public"."t3-app-template_calendar"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
DO $$ BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 't3-app-template_event' AND column_name = 'buildingId'
  ) THEN
    ALTER TABLE "t3-app-template_event" ADD CONSTRAINT "t3-app-template_event_buildingId_t3-app-template_building_id_fk" FOREIGN KEY ("buildingId") REFERENCES "public"."t3-app-template_building"("id") ON DELETE set null ON UPDATE no action;
  END IF;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
DO $$ BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 't3-app-template_event' AND column_name = 'assigneeProfileId'
  ) THEN
    ALTER TABLE "t3-app-template_event" ADD CONSTRAINT "t3-app-template_event_assigneeProfileId_t3-app-template_profile_id_fk" FOREIGN KEY ("assigneeProfileId") REFERENCES "public"."t3-app-template_profile"("id") ON DELETE set null ON UPDATE no action;
  END IF;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "t3-app-template_organization_role" ADD CONSTRAINT "t3-app-template_organization_role_userId_t3-app-template_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."t3-app-template_user"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "t3-app-template_organization_role" ADD CONSTRAINT "t3-app-template_organization_role_profileId_t3-app-template_profile_id_fk" FOREIGN KEY ("profileId") REFERENCES "public"."t3-app-template_profile"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "t3-app-template_profile" ADD CONSTRAINT "t3-app-template_profile_userId_t3-app-template_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."t3-app-template_user"("id") ON DELETE set null ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "t3-app-template_room" ADD CONSTRAINT "t3-app-template_room_buildingId_t3-app-template_building_id_fk" FOREIGN KEY ("buildingId") REFERENCES "public"."t3-app-template_building"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "t3-app-template_theme_palette" ADD CONSTRAINT "t3-app-template_theme_palette_businessId_t3-app-template_business_id_fk" FOREIGN KEY ("businessId") REFERENCES "public"."t3-app-template_business"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "t3-app-template_theme_palette" ADD CONSTRAINT "t3-app-template_theme_palette_createdByUserId_t3-app-template_user_id_fk" FOREIGN KEY ("createdByUserId") REFERENCES "public"."t3-app-template_user"("id") ON DELETE set null ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "t3-app-template_theme_profile" ADD CONSTRAINT "t3-app-template_theme_profile_businessId_t3-app-template_business_id_fk" FOREIGN KEY ("businessId") REFERENCES "public"."t3-app-template_business"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "t3-app-template_theme_profile" ADD CONSTRAINT "t3-app-template_theme_profile_paletteId_t3-app-template_theme_palette_id_fk" FOREIGN KEY ("paletteId") REFERENCES "public"."t3-app-template_theme_palette"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "building_business_idx" ON "t3-app-template_building" USING btree ("businessId");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "building_business_acronym_idx" ON "t3-app-template_building" USING btree ("businessId","acronym");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "business_name_unique" ON "t3-app-template_business" USING btree ("name");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "calendar_user_idx" ON "t3-app-template_calendar" USING btree ("userId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "department_business_idx" ON "t3-app-template_department" USING btree ("businessId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "department_parent_idx" ON "t3-app-template_department" USING btree ("parentDepartmentId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "attendee_event_idx" ON "t3-app-template_event_attendee" USING btree ("eventId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "attendee_profile_idx" ON "t3-app-template_event_attendee" USING btree ("profileId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "event_hour_log_event_idx" ON "t3-app-template_event_hour_log" USING btree ("eventId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "event_hour_log_profile_idx" ON "t3-app-template_event_hour_log" USING btree ("loggedByProfileId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "reminder_event_idx" ON "t3-app-template_event_reminder" USING btree ("eventId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "zendesk_confirmation_event_idx" ON "t3-app-template_event_zendesk_confirmation" USING btree ("eventId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "zendesk_confirmation_profile_idx" ON "t3-app-template_event_zendesk_confirmation" USING btree ("profileId");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "zendesk_confirmation_event_profile_idx" ON "t3-app-template_event_zendesk_confirmation" USING btree ("eventId","profileId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "event_calendar_idx" ON "t3-app-template_event" USING btree ("calendarId");--> statement-breakpoint
DO $$ BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 't3-app-template_event' AND column_name = 'buildingId'
  ) THEN
    CREATE INDEX IF NOT EXISTS "event_building_idx" ON "t3-app-template_event" USING btree ("buildingId");
  END IF;
END $$;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "event_start_idx" ON "t3-app-template_event" USING btree ("startDatetime");--> statement-breakpoint
DO $$ BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 't3-app-template_event' AND column_name = 'assigneeProfileId'
  ) THEN
    CREATE INDEX IF NOT EXISTS "event_assignee_idx" ON "t3-app-template_event" USING btree ("assigneeProfileId");
  END IF;
END $$;--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "event_event_code_unique" ON "t3-app-template_event" USING btree ("eventCode");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "organization_role_user_idx" ON "t3-app-template_organization_role" USING btree ("userId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "organization_role_scope_idx" ON "t3-app-template_organization_role" USING btree ("scopeType","scopeId");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "organization_role_unique" ON "t3-app-template_organization_role" USING btree ("userId","scopeType","scopeId","roleType");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "name_idx" ON "t3-app-template_post" USING btree ("name");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "profile_email_unique" ON "t3-app-template_profile" USING btree ("email");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "profile_user_unique" ON "t3-app-template_profile" USING btree ("userId") WHERE "t3-app-template_profile"."userId" IS NOT NULL;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "room_building_idx" ON "t3-app-template_room" USING btree ("buildingId");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "room_building_number_idx" ON "t3-app-template_room" USING btree ("buildingId","roomNumber");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "theme_palette_business_idx" ON "t3-app-template_theme_palette" USING btree ("businessId");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "theme_palette_business_name_idx" ON "t3-app-template_theme_palette" USING btree ("businessId","name");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "theme_profile_scope_idx" ON "t3-app-template_theme_profile" USING btree ("businessId","scopeType","scopeId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "theme_profile_palette_idx" ON "t3-app-template_theme_profile" USING btree ("paletteId");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "user_username_unique" ON "t3-app-template_user" USING btree ("username");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "user_email_unique" ON "t3-app-template_user" USING btree ("email");
