DO $$ BEGIN
  ALTER TYPE "public"."organization_role_type" ADD VALUE 'co_admin' BEFORE 'manager';
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;--> statement-breakpoint
DO $$
BEGIN
	IF NOT EXISTS (
		SELECT 1
		FROM pg_class c
		JOIN pg_namespace n ON n.oid = c.relnamespace
		WHERE c.relname = 't3-app-template_audit_log'
		AND n.nspname = current_schema()
		AND c.relkind = 'r'
	) THEN
		CREATE TABLE "t3-app-template_audit_log" (
			"id" integer PRIMARY KEY,
			"businessId" integer,
			"actorUserId" integer,
			"actorProfileId" integer,
			"action" varchar(120) NOT NULL,
			"targetType" varchar(120) NOT NULL,
			"targetId" integer,
			"scopeType" "organization_scope_type",
			"scopeId" integer,
			"metadata" jsonb,
			"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
		);

		IF EXISTS (
			SELECT 1
			FROM pg_class c
			JOIN pg_namespace n ON n.oid = c.relnamespace
			WHERE c.relname = 't3-app-template_audit_log_id_seq'
			AND n.nspname = current_schema()
			AND c.relkind = 'S'
		) THEN
			ALTER SEQUENCE "t3-app-template_audit_log_id_seq" OWNED BY "t3-app-template_audit_log"."id";
			ALTER TABLE "t3-app-template_audit_log" ALTER COLUMN "id" SET DEFAULT nextval('"t3-app-template_audit_log_id_seq"'::regclass);
		ELSE
			ALTER TABLE "t3-app-template_audit_log"
				ALTER COLUMN "id"
				ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "t3-app-template_audit_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);
		END IF;
	END IF;
END $$;
--> statement-breakpoint
DO $$
BEGIN
	IF NOT EXISTS (
		SELECT 1
		FROM pg_class c
		JOIN pg_namespace n ON n.oid = c.relnamespace
		WHERE c.relname = 't3-app-template_event_co_owner'
		AND n.nspname = current_schema()
		AND c.relkind = 'r'
	) THEN
		CREATE TABLE "t3-app-template_event_co_owner" (
			"id" integer PRIMARY KEY,
			"eventId" integer NOT NULL,
			"profileId" integer NOT NULL,
			"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
		);

		IF EXISTS (
			SELECT 1
			FROM pg_class c
			JOIN pg_namespace n ON n.oid = c.relnamespace
			WHERE c.relname = 't3-app-template_event_co_owner_id_seq'
			AND n.nspname = current_schema()
			AND c.relkind = 'S'
		) THEN
			ALTER SEQUENCE "t3-app-template_event_co_owner_id_seq" OWNED BY "t3-app-template_event_co_owner"."id";
			ALTER TABLE "t3-app-template_event_co_owner" ALTER COLUMN "id" SET DEFAULT nextval('"t3-app-template_event_co_owner_id_seq"'::regclass);
		ELSE
			ALTER TABLE "t3-app-template_event_co_owner"
				ALTER COLUMN "id"
				ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "t3-app-template_event_co_owner_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);
		END IF;
	END IF;
END $$;
--> statement-breakpoint
DO $$
BEGIN
	IF NOT EXISTS (
		SELECT 1
		FROM pg_class c
		JOIN pg_namespace n ON n.oid = c.relnamespace
		WHERE c.relname = 't3-app-template_visibility_grant'
		AND n.nspname = current_schema()
		AND c.relkind = 'r'
	) THEN
		CREATE TABLE "t3-app-template_visibility_grant" (
			"id" integer PRIMARY KEY,
			"userId" integer NOT NULL,
			"scopeType" "organization_scope_type" NOT NULL,
			"scopeId" integer NOT NULL,
			"createdByUserId" integer,
			"reason" varchar(255) DEFAULT '' NOT NULL,
			"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
		);

		IF EXISTS (
			SELECT 1
			FROM pg_class c
			JOIN pg_namespace n ON n.oid = c.relnamespace
			WHERE c.relname = 't3-app-template_visibility_grant_id_seq'
			AND n.nspname = current_schema()
			AND c.relkind = 'S'
		) THEN
			ALTER SEQUENCE "t3-app-template_visibility_grant_id_seq" OWNED BY "t3-app-template_visibility_grant"."id";
			ALTER TABLE "t3-app-template_visibility_grant" ALTER COLUMN "id" SET DEFAULT nextval('"t3-app-template_visibility_grant_id_seq"'::regclass);
		ELSE
			ALTER TABLE "t3-app-template_visibility_grant"
				ALTER COLUMN "id"
				ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "t3-app-template_visibility_grant_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);
		END IF;
	END IF;
END $$;
--> statement-breakpoint
ALTER TABLE "t3-app-template_event" ADD COLUMN IF NOT EXISTS "ownerProfileId" integer;--> statement-breakpoint
ALTER TABLE "t3-app-template_event" ADD COLUMN IF NOT EXISTS "scopeType" "organization_scope_type";--> statement-breakpoint
ALTER TABLE "t3-app-template_event" ADD COLUMN IF NOT EXISTS "scopeId" integer;--> statement-breakpoint
UPDATE "t3-app-template_event"
SET "scopeType" = 'business'
WHERE "scopeType" IS NULL;--> statement-breakpoint
UPDATE "t3-app-template_event"
SET "scopeId" = (SELECT "id" FROM "t3-app-template_business" ORDER BY "id" LIMIT 1)
WHERE "scopeId" IS NULL;--> statement-breakpoint
ALTER TABLE "t3-app-template_event" ALTER COLUMN "scopeType" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "t3-app-template_event" ALTER COLUMN "scopeId" SET NOT NULL;--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 't3-app-template_audit_log'::regclass
    AND contype = 'f'
    AND conname LIKE 't3-app-template_audit_log_businessId_t3-app-template_business%'
  ) THEN
    ALTER TABLE "t3-app-template_audit_log" ADD CONSTRAINT "t3-app-template_audit_log_businessId_t3-app-template_business_id_fk" FOREIGN KEY ("businessId") REFERENCES "public"."t3-app-template_business"("id") ON DELETE set null ON UPDATE no action;
  END IF;
END $$;--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 't3-app-template_audit_log'::regclass
    AND contype = 'f'
    AND conname LIKE 't3-app-template_audit_log_actorUserId_t3-app-template_user%'
  ) THEN
    ALTER TABLE "t3-app-template_audit_log" ADD CONSTRAINT "t3-app-template_audit_log_actorUserId_t3-app-template_user_id_fk" FOREIGN KEY ("actorUserId") REFERENCES "public"."t3-app-template_user"("id") ON DELETE set null ON UPDATE no action;
  END IF;
END $$;--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 't3-app-template_audit_log'::regclass
    AND contype = 'f'
    AND conname LIKE 't3-app-template_audit_log_actorProfileId_t3-app-template_profile%'
  ) THEN
    ALTER TABLE "t3-app-template_audit_log" ADD CONSTRAINT "t3-app-template_audit_log_actorProfileId_t3-app-template_profile_id_fk" FOREIGN KEY ("actorProfileId") REFERENCES "public"."t3-app-template_profile"("id") ON DELETE set null ON UPDATE no action;
  END IF;
END $$;--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 't3-app-template_event_co_owner'::regclass
    AND contype = 'f'
    AND conname LIKE 't3-app-template_event_co_owner_eventId_t3-app-template_event%'
  ) THEN
    ALTER TABLE "t3-app-template_event_co_owner" ADD CONSTRAINT "t3-app-template_event_co_owner_eventId_t3-app-template_event_id_fk" FOREIGN KEY ("eventId") REFERENCES "public"."t3-app-template_event"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 't3-app-template_event_co_owner'::regclass
    AND contype = 'f'
    AND conname LIKE 't3-app-template_event_co_owner_profileId_t3-app-template_profile%'
  ) THEN
    ALTER TABLE "t3-app-template_event_co_owner" ADD CONSTRAINT "t3-app-template_event_co_owner_profileId_t3-app-template_profile_id_fk" FOREIGN KEY ("profileId") REFERENCES "public"."t3-app-template_profile"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 't3-app-template_visibility_grant'::regclass
    AND contype = 'f'
    AND conname LIKE 't3-app-template_visibility_grant_userId_t3-app-template_user%'
  ) THEN
    ALTER TABLE "t3-app-template_visibility_grant" ADD CONSTRAINT "t3-app-template_visibility_grant_userId_t3-app-template_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."t3-app-template_user"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 't3-app-template_visibility_grant'::regclass
    AND contype = 'f'
    AND conname LIKE 't3-app-template_visibility_grant_createdByUserId_t3-app-template_user%'
  ) THEN
    ALTER TABLE "t3-app-template_visibility_grant" ADD CONSTRAINT "t3-app-template_visibility_grant_createdByUserId_t3-app-template_user_id_fk" FOREIGN KEY ("createdByUserId") REFERENCES "public"."t3-app-template_user"("id") ON DELETE set null ON UPDATE no action;
  END IF;
END $$;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "audit_log_business_idx" ON "t3-app-template_audit_log" USING btree ("businessId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "audit_log_actor_idx" ON "t3-app-template_audit_log" USING btree ("actorUserId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "audit_log_scope_idx" ON "t3-app-template_audit_log" USING btree ("scopeType","scopeId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "event_co_owner_event_idx" ON "t3-app-template_event_co_owner" USING btree ("eventId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "event_co_owner_profile_idx" ON "t3-app-template_event_co_owner" USING btree ("profileId");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "event_co_owner_unique" ON "t3-app-template_event_co_owner" USING btree ("eventId","profileId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "visibility_grant_user_idx" ON "t3-app-template_visibility_grant" USING btree ("userId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "visibility_grant_scope_idx" ON "t3-app-template_visibility_grant" USING btree ("scopeType","scopeId");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "visibility_grant_unique" ON "t3-app-template_visibility_grant" USING btree ("userId","scopeType","scopeId");--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 't3-app-template_event'::regclass
    AND contype = 'f'
    AND conname LIKE 't3-app-template_event_ownerProfileId_t3-app-template_profile%'
  ) THEN
    ALTER TABLE "t3-app-template_event" ADD CONSTRAINT "t3-app-template_event_ownerProfileId_t3-app-template_profile_id_fk" FOREIGN KEY ("ownerProfileId") REFERENCES "public"."t3-app-template_profile"("id") ON DELETE set null ON UPDATE no action;
  END IF;
END $$;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "event_scope_idx" ON "t3-app-template_event" USING btree ("scopeType","scopeId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "event_owner_idx" ON "t3-app-template_event" USING btree ("ownerProfileId");
