DO $$ BEGIN
  ALTER TYPE "public"."organization_role_type" ADD VALUE 'co_admin' BEFORE 'manager';
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;--> statement-breakpoint
CREATE TABLE "t3-app-template_audit_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "t3-app-template_audit_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"businessId" integer,
	"actorUserId" integer,
	"actorProfileId" integer,
	"action" varchar(120) NOT NULL,
	"targetType" varchar(120) NOT NULL,
	"targetId" integer,
	"scopeType" "organization_scope_type",
	"scopeId" integer,
	"metadata" jsonb,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "t3-app-template_event_co_owner" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "t3-app-template_event_co_owner_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"eventId" integer NOT NULL,
	"profileId" integer NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "t3-app-template_visibility_grant" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "t3-app-template_visibility_grant_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"scopeType" "organization_scope_type" NOT NULL,
	"scopeId" integer NOT NULL,
	"createdByUserId" integer,
	"reason" varchar(255) DEFAULT '' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
ALTER TABLE "t3-app-template_event" ADD COLUMN "ownerProfileId" integer;--> statement-breakpoint
ALTER TABLE "t3-app-template_event" ADD COLUMN "scopeType" "organization_scope_type";--> statement-breakpoint
ALTER TABLE "t3-app-template_event" ADD COLUMN "scopeId" integer;--> statement-breakpoint
UPDATE "t3-app-template_event"
SET "scopeType" = 'business'
WHERE "scopeType" IS NULL;--> statement-breakpoint
UPDATE "t3-app-template_event"
SET "scopeId" = (SELECT "id" FROM "t3-app-template_business" ORDER BY "id" LIMIT 1)
WHERE "scopeId" IS NULL;--> statement-breakpoint
ALTER TABLE "t3-app-template_event" ALTER COLUMN "scopeType" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "t3-app-template_event" ALTER COLUMN "scopeId" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "t3-app-template_audit_log" ADD CONSTRAINT "t3-app-template_audit_log_businessId_t3-app-template_business_id_fk" FOREIGN KEY ("businessId") REFERENCES "public"."t3-app-template_business"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "t3-app-template_audit_log" ADD CONSTRAINT "t3-app-template_audit_log_actorUserId_t3-app-template_user_id_fk" FOREIGN KEY ("actorUserId") REFERENCES "public"."t3-app-template_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "t3-app-template_audit_log" ADD CONSTRAINT "t3-app-template_audit_log_actorProfileId_t3-app-template_profile_id_fk" FOREIGN KEY ("actorProfileId") REFERENCES "public"."t3-app-template_profile"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "t3-app-template_event_co_owner" ADD CONSTRAINT "t3-app-template_event_co_owner_eventId_t3-app-template_event_id_fk" FOREIGN KEY ("eventId") REFERENCES "public"."t3-app-template_event"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "t3-app-template_event_co_owner" ADD CONSTRAINT "t3-app-template_event_co_owner_profileId_t3-app-template_profile_id_fk" FOREIGN KEY ("profileId") REFERENCES "public"."t3-app-template_profile"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "t3-app-template_visibility_grant" ADD CONSTRAINT "t3-app-template_visibility_grant_userId_t3-app-template_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."t3-app-template_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "t3-app-template_visibility_grant" ADD CONSTRAINT "t3-app-template_visibility_grant_createdByUserId_t3-app-template_user_id_fk" FOREIGN KEY ("createdByUserId") REFERENCES "public"."t3-app-template_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "audit_log_business_idx" ON "t3-app-template_audit_log" USING btree ("businessId");--> statement-breakpoint
CREATE INDEX "audit_log_actor_idx" ON "t3-app-template_audit_log" USING btree ("actorUserId");--> statement-breakpoint
CREATE INDEX "audit_log_scope_idx" ON "t3-app-template_audit_log" USING btree ("scopeType","scopeId");--> statement-breakpoint
CREATE INDEX "event_co_owner_event_idx" ON "t3-app-template_event_co_owner" USING btree ("eventId");--> statement-breakpoint
CREATE INDEX "event_co_owner_profile_idx" ON "t3-app-template_event_co_owner" USING btree ("profileId");--> statement-breakpoint
CREATE UNIQUE INDEX "event_co_owner_unique" ON "t3-app-template_event_co_owner" USING btree ("eventId","profileId");--> statement-breakpoint
CREATE INDEX "visibility_grant_user_idx" ON "t3-app-template_visibility_grant" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "visibility_grant_scope_idx" ON "t3-app-template_visibility_grant" USING btree ("scopeType","scopeId");--> statement-breakpoint
CREATE UNIQUE INDEX "visibility_grant_unique" ON "t3-app-template_visibility_grant" USING btree ("userId","scopeType","scopeId");--> statement-breakpoint
ALTER TABLE "t3-app-template_event" ADD CONSTRAINT "t3-app-template_event_ownerProfileId_t3-app-template_profile_id_fk" FOREIGN KEY ("ownerProfileId") REFERENCES "public"."t3-app-template_profile"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "event_scope_idx" ON "t3-app-template_event" USING btree ("scopeType","scopeId");--> statement-breakpoint
CREATE INDEX "event_owner_idx" ON "t3-app-template_event" USING btree ("ownerProfileId");
