CREATE TABLE "t3-app-template_event_room" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "t3-app-template_event_room_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"eventId" integer NOT NULL,
	"roomId" integer NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
ALTER TABLE "t3-app-template_event_room" ADD CONSTRAINT "t3-app-template_event_room_eventId_t3-app-template_event_id_fk" FOREIGN KEY ("eventId") REFERENCES "public"."t3-app-template_event"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "t3-app-template_event_room" ADD CONSTRAINT "t3-app-template_event_room_roomId_t3-app-template_room_id_fk" FOREIGN KEY ("roomId") REFERENCES "public"."t3-app-template_room"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "event_room_event_idx" ON "t3-app-template_event_room" USING btree ("eventId");--> statement-breakpoint
CREATE INDEX "event_room_room_idx" ON "t3-app-template_event_room" USING btree ("roomId");--> statement-breakpoint
CREATE UNIQUE INDEX "event_room_event_room_unique" ON "t3-app-template_event_room" USING btree ("eventId","roomId");