ALTER TABLE "t3-app-template_business"
  ADD COLUMN IF NOT EXISTS "timeZone" varchar(100) DEFAULT 'UTC' NOT NULL;
--> statement-breakpoint
ALTER TABLE "t3-app-template_business"
  ADD COLUMN IF NOT EXISTS "dateFormatConfig" jsonb DEFAULT '{"dateKeyPattern":"YYYYMMDD","isoDatePattern":"YYYY-MM-DD","usDatePattern":"MM/DD/YYYY","longDatePattern":"MMMM D, YYYY","monthYearPattern":"MMMM YYYY","yearMonthLabelPattern":"YYYY-MM","yearQuarterLabelPattern":"YYYY-[Q]Q","quarterYearLabelPattern":"[Q]Q YYYY","isoDateTimePattern":"YYYY-MM-DD[T]HH:mm:ss","usDateTimePattern":"MM/DD/YYYY hh:mm:ss A"}'::jsonb NOT NULL;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "t3-app-template_date_time" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "instantUtc" timestamp with time zone NOT NULL,
  "timeZone" varchar(100) NOT NULL,
  "dateKey" varchar(32) NOT NULL,
  "fullDate" date NOT NULL,
  "calendarDate" date NOT NULL,
  "dayOfWeekNumber" integer NOT NULL,
  "dayOfWeekName" varchar(24) NOT NULL,
  "year" integer NOT NULL,
  "quarter" integer NOT NULL,
  "month" integer NOT NULL,
  "monthLabel" varchar(16) NOT NULL,
  "monthName" varchar(24) NOT NULL,
  "monthShortName" varchar(16) NOT NULL,
  "isoWeekYear" integer NOT NULL,
  "isoWeek" integer NOT NULL,
  "isoWeekLabel" varchar(16) NOT NULL,
  "dayOfMonth" integer NOT NULL,
  "dayOfYear" integer NOT NULL,
  "weekOfYear" integer NOT NULL,
  "dayOfWeekIso" integer NOT NULL,
  "dayLabel" varchar(16) NOT NULL,
  "monthNumber" integer NOT NULL,
  "quarterNumber" integer NOT NULL,
  "yearMonthKey" varchar(16) NOT NULL,
  "yearMonthLabel" varchar(24) NOT NULL,
  "yearQuarterLabel" varchar(24) NOT NULL,
  "weekStartDate" date NOT NULL,
  "weekEndDate" date NOT NULL,
  "monthStartDate" date NOT NULL,
  "monthEndDate" date NOT NULL,
  "quarterStartDate" date NOT NULL,
  "quarterEndDate" date NOT NULL,
  "yearStartDate" date NOT NULL,
  "yearEndDate" date NOT NULL,
  "isWeekday" boolean NOT NULL,
  "isWeekend" boolean NOT NULL,
  "isBusinessDay" boolean NOT NULL,
  "isMonthStart" boolean NOT NULL,
  "isMonthEnd" boolean NOT NULL,
  "isQuarterStart" boolean NOT NULL,
  "isQuarterEnd" boolean NOT NULL,
  "isYearStart" boolean NOT NULL,
  "isYearEnd" boolean NOT NULL,
  "hour24" integer NOT NULL,
  "minute" integer NOT NULL,
  "second" integer NOT NULL,
  "isoDate" varchar(64) NOT NULL,
  "isoDateTime" varchar(64) NOT NULL,
  "usDate" varchar(64) NOT NULL,
  "usDateTime" varchar(96) NOT NULL,
  "dateIsoFormat" varchar(64) NOT NULL,
  "dateUsFormat" varchar(64) NOT NULL,
  "dateLongFormat" varchar(96) NOT NULL,
  "monthYearText" varchar(64) NOT NULL,
  "quarterYearLabel" varchar(24) NOT NULL,
  "previousDate" date NOT NULL,
  "nextDate" date NOT NULL,
  "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "date_time_instant_timezone_unique"
  ON "t3-app-template_date_time" ("instantUtc", "timeZone");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "date_time_timezone_instant_idx"
  ON "t3-app-template_date_time" ("timeZone", "instantUtc");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "date_time_timezone_calendar_idx"
  ON "t3-app-template_date_time" ("timeZone", "year", "month", "dayOfMonth");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "date_time_timezone_week_idx"
  ON "t3-app-template_date_time" ("timeZone", "isoWeekYear", "isoWeek");
--> statement-breakpoint
ALTER TABLE "t3-app-template_event"
  ADD COLUMN IF NOT EXISTS "startDateTimeId" integer;
--> statement-breakpoint
ALTER TABLE "t3-app-template_event"
  ADD COLUMN IF NOT EXISTS "endDateTimeId" integer;
--> statement-breakpoint
ALTER TABLE "t3-app-template_event"
  ADD COLUMN IF NOT EXISTS "eventStartDateTimeId" integer;
--> statement-breakpoint
ALTER TABLE "t3-app-template_event"
  ADD COLUMN IF NOT EXISTS "eventEndDateTimeId" integer;
--> statement-breakpoint
ALTER TABLE "t3-app-template_event"
  ADD COLUMN IF NOT EXISTS "setupDateTimeId" integer;
--> statement-breakpoint
WITH settings AS (
  SELECT COALESCE(
    (SELECT "timeZone" FROM "t3-app-template_business" ORDER BY "id" LIMIT 1),
    'UTC'
  ) AS timezone_name
),
source_instants AS (
  SELECT DISTINCT "startDatetime" AS instant_utc
  FROM "t3-app-template_event"
  UNION
  SELECT DISTINCT "endDatetime" AS instant_utc
  FROM "t3-app-template_event"
  UNION
  SELECT DISTINCT "eventStartTime" AS instant_utc
  FROM "t3-app-template_event"
  WHERE "eventStartTime" IS NOT NULL
  UNION
  SELECT DISTINCT "eventEndTime" AS instant_utc
  FROM "t3-app-template_event"
  WHERE "eventEndTime" IS NOT NULL
  UNION
  SELECT DISTINCT "setupTime" AS instant_utc
  FROM "t3-app-template_event"
  WHERE "setupTime" IS NOT NULL
),
prepared AS (
  SELECT
    s.instant_utc,
    cfg.timezone_name,
    timezone(cfg.timezone_name, s.instant_utc) AS local_ts,
    timezone(cfg.timezone_name, s.instant_utc)::date AS local_date
  FROM source_instants s
  CROSS JOIN settings cfg
  WHERE s.instant_utc IS NOT NULL
)
INSERT INTO "t3-app-template_date_time" (
  "instantUtc",
  "timeZone",
  "dateKey",
  "fullDate",
  "calendarDate",
  "dayOfWeekNumber",
  "dayOfWeekName",
  "year",
  "quarter",
  "month",
  "monthLabel",
  "monthName",
  "monthShortName",
  "isoWeekYear",
  "isoWeek",
  "isoWeekLabel",
  "dayOfMonth",
  "dayOfYear",
  "weekOfYear",
  "dayOfWeekIso",
  "dayLabel",
  "monthNumber",
  "quarterNumber",
  "yearMonthKey",
  "yearMonthLabel",
  "yearQuarterLabel",
  "weekStartDate",
  "weekEndDate",
  "monthStartDate",
  "monthEndDate",
  "quarterStartDate",
  "quarterEndDate",
  "yearStartDate",
  "yearEndDate",
  "isWeekday",
  "isWeekend",
  "isBusinessDay",
  "isMonthStart",
  "isMonthEnd",
  "isQuarterStart",
  "isQuarterEnd",
  "isYearStart",
  "isYearEnd",
  "hour24",
  "minute",
  "second",
  "isoDate",
  "isoDateTime",
  "usDate",
  "usDateTime",
  "dateIsoFormat",
  "dateUsFormat",
  "dateLongFormat",
  "monthYearText",
  "quarterYearLabel",
  "previousDate",
  "nextDate"
)
SELECT
  instant_utc,
  timezone_name,
  to_char(local_ts, 'YYYYMMDD'),
  local_date,
  local_date,
  extract(isodow from local_ts)::int,
  to_char(local_ts, 'FMDay'),
  extract(year from local_ts)::int,
  extract(quarter from local_ts)::int,
  extract(month from local_ts)::int,
  to_char(local_ts, 'Mon'),
  to_char(local_ts, 'FMMonth'),
  to_char(local_ts, 'Mon'),
  extract(isoyear from local_ts)::int,
  extract(week from local_ts)::int,
  concat(extract(isoyear from local_ts)::int, '-W', lpad(extract(week from local_ts)::int::text, 2, '0')),
  extract(day from local_ts)::int,
  extract(doy from local_ts)::int,
  extract(week from local_ts)::int,
  extract(isodow from local_ts)::int,
  to_char(local_ts, 'Dy'),
  extract(month from local_ts)::int,
  extract(quarter from local_ts)::int,
  concat(extract(year from local_ts)::int, lpad(extract(month from local_ts)::int::text, 2, '0')),
  to_char(local_ts, 'YYYY-MM'),
  concat(extract(year from local_ts)::int, '-Q', extract(quarter from local_ts)::int),
  (local_date - (extract(isodow from local_ts)::int - 1)),
  (local_date + (7 - extract(isodow from local_ts)::int)),
  date_trunc('month', local_ts)::date,
  (date_trunc('month', local_ts) + interval '1 month - 1 day')::date,
  date_trunc('quarter', local_ts)::date,
  (date_trunc('quarter', local_ts) + interval '3 months - 1 day')::date,
  date_trunc('year', local_ts)::date,
  (date_trunc('year', local_ts) + interval '1 year - 1 day')::date,
  extract(isodow from local_ts)::int <= 5,
  extract(isodow from local_ts)::int >= 6,
  extract(isodow from local_ts)::int <= 5,
  extract(day from local_ts)::int = 1,
  local_date = (date_trunc('month', local_ts) + interval '1 month - 1 day')::date,
  local_date = date_trunc('quarter', local_ts)::date,
  local_date = (date_trunc('quarter', local_ts) + interval '3 months - 1 day')::date,
  local_date = date_trunc('year', local_ts)::date,
  local_date = (date_trunc('year', local_ts) + interval '1 year - 1 day')::date,
  extract(hour from local_ts)::int,
  extract(minute from local_ts)::int,
  floor(extract(second from local_ts))::int,
  to_char(local_ts, 'YYYY-MM-DD'),
  to_char(local_ts, 'YYYY-MM-DD"T"HH24:MI:SS'),
  to_char(local_ts, 'MM/DD/YYYY'),
  to_char(local_ts, 'MM/DD/YYYY HH12:MI:SS AM'),
  to_char(local_ts, 'YYYY-MM-DD'),
  to_char(local_ts, 'MM/DD/YYYY'),
  to_char(local_ts, 'FMMonth FMDD, YYYY'),
  to_char(local_ts, 'FMMonth YYYY'),
  concat('Q', extract(quarter from local_ts)::int, ' ', extract(year from local_ts)::int),
  (local_date - 1),
  (local_date + 1)
FROM prepared
ON CONFLICT ("instantUtc", "timeZone") DO NOTHING;
--> statement-breakpoint
WITH settings AS (
  SELECT COALESCE(
    (SELECT "timeZone" FROM "t3-app-template_business" ORDER BY "id" LIMIT 1),
    'UTC'
  ) AS timezone_name
)
UPDATE "t3-app-template_event" e
SET
  "startDateTimeId" = (
    SELECT dt."id"
    FROM "t3-app-template_date_time" dt, settings s
    WHERE dt."instantUtc" = e."startDatetime" AND dt."timeZone" = s.timezone_name
    LIMIT 1
  ),
  "endDateTimeId" = (
    SELECT dt."id"
    FROM "t3-app-template_date_time" dt, settings s
    WHERE dt."instantUtc" = e."endDatetime" AND dt."timeZone" = s.timezone_name
    LIMIT 1
  ),
  "eventStartDateTimeId" = (
    SELECT dt."id"
    FROM "t3-app-template_date_time" dt, settings s
    WHERE dt."instantUtc" = e."eventStartTime" AND dt."timeZone" = s.timezone_name
    LIMIT 1
  ),
  "eventEndDateTimeId" = (
    SELECT dt."id"
    FROM "t3-app-template_date_time" dt, settings s
    WHERE dt."instantUtc" = e."eventEndTime" AND dt."timeZone" = s.timezone_name
    LIMIT 1
  ),
  "setupDateTimeId" = (
    SELECT dt."id"
    FROM "t3-app-template_date_time" dt, settings s
    WHERE dt."instantUtc" = e."setupTime" AND dt."timeZone" = s.timezone_name
    LIMIT 1
  );
--> statement-breakpoint
ALTER TABLE "t3-app-template_event"
  ALTER COLUMN "startDateTimeId" SET NOT NULL;
--> statement-breakpoint
ALTER TABLE "t3-app-template_event"
  ALTER COLUMN "endDateTimeId" SET NOT NULL;
--> statement-breakpoint
ALTER TABLE "t3-app-template_event"
  ADD CONSTRAINT "event_start_date_time_fk"
  FOREIGN KEY ("startDateTimeId")
  REFERENCES "t3-app-template_date_time"("id")
  ON DELETE RESTRICT ON UPDATE NO ACTION;
--> statement-breakpoint
ALTER TABLE "t3-app-template_event"
  ADD CONSTRAINT "event_end_date_time_fk"
  FOREIGN KEY ("endDateTimeId")
  REFERENCES "t3-app-template_date_time"("id")
  ON DELETE RESTRICT ON UPDATE NO ACTION;
--> statement-breakpoint
ALTER TABLE "t3-app-template_event"
  ADD CONSTRAINT "event_event_start_date_time_fk"
  FOREIGN KEY ("eventStartDateTimeId")
  REFERENCES "t3-app-template_date_time"("id")
  ON DELETE SET NULL ON UPDATE NO ACTION;
--> statement-breakpoint
ALTER TABLE "t3-app-template_event"
  ADD CONSTRAINT "event_event_end_date_time_fk"
  FOREIGN KEY ("eventEndDateTimeId")
  REFERENCES "t3-app-template_date_time"("id")
  ON DELETE SET NULL ON UPDATE NO ACTION;
--> statement-breakpoint
ALTER TABLE "t3-app-template_event"
  ADD CONSTRAINT "event_setup_date_time_fk"
  FOREIGN KEY ("setupDateTimeId")
  REFERENCES "t3-app-template_date_time"("id")
  ON DELETE SET NULL ON UPDATE NO ACTION;
--> statement-breakpoint
DROP INDEX IF EXISTS "event_start_idx";
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "event_start_datetime_fk_idx"
  ON "t3-app-template_event" ("startDateTimeId");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "event_end_datetime_fk_idx"
  ON "t3-app-template_event" ("endDateTimeId");
--> statement-breakpoint
ALTER TABLE "t3-app-template_event"
  DROP COLUMN IF EXISTS "startDatetime",
  DROP COLUMN IF EXISTS "endDatetime",
  DROP COLUMN IF EXISTS "eventStartTime",
  DROP COLUMN IF EXISTS "eventEndTime",
  DROP COLUMN IF EXISTS "setupTime";
