import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { Providers } from "./providers";
import { SidebarNav } from "./_components/SidebarNav";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body data-theme="dark" className="bg-surface-canvas text-ink-primary antialiased">
        <Providers>
          <div className="flex min-h-screen">
            <SidebarNav />
            <main className="min-h-screen flex-1 bg-surface-canvas">{children}</main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
