import "~/styles/globals.css";

import { type Metadata } from "next";
import { getServerSession } from "next-auth";
import { Geist } from "next/font/google";

import { Providers } from "./providers";
import { AppShell } from "./_components/AppShell";
import { authOptions } from "~/server/auth";
import { resolvePalette } from "~/server/services/theme";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await getServerSession(authOptions);
  const resolvedPalette = await resolvePalette({
    userId: session?.user?.id ? Number(session.user.id) : null,
  });

  return (
    <html lang="en" className={`${geist.variable} h-full`}>
      <body data-theme="dark" className="h-full bg-surface-canvas text-ink-primary antialiased">
        <Providers palette={resolvedPalette}>
          <AppShell user={session?.user ?? null}>{children}</AppShell>
        </Providers>
      </body>
    </html>
  );
}
