import test from "node:test";
import assert from "node:assert/strict";

import { __hourLogExportTestUtils } from "~/server/services/hour-log-export";

test("hour log export creates distinct sheets for different profiles with the same display label", () => {
  const baseDate = new Date("2026-03-28T12:00:00.000Z");
  const data = {
    logs: [
      {
        id: 1,
        eventId: 101,
        loggedByProfileId: 11,
        startTime: baseDate,
        endTime: new Date("2026-03-28T13:00:00.000Z"),
        durationMinutes: 60,
        createdAt: baseDate,
      },
      {
        id: 2,
        eventId: 102,
        loggedByProfileId: 22,
        startTime: baseDate,
        endTime: new Date("2026-03-28T14:00:00.000Z"),
        durationMinutes: 120,
        createdAt: baseDate,
      },
    ],
    events: [
      {
        id: 101,
        calendarId: 201,
        buildingId: null,
        assigneeProfileId: null,
        ownerProfileId: null,
        scopeType: "business" as const,
        scopeId: 1,
        eventCode: "1111111",
        title: "Event A",
        description: null,
        location: null,
        isVirtual: false,
        isAllDay: false,
        startDatetime: baseDate,
        endDatetime: new Date("2026-03-28T13:00:00.000Z"),
        recurrenceRule: null,
        participantCount: null,
        technicianNeeded: false,
        requestCategory: null,
        equipmentNeeded: null,
        eventStartTime: null,
        eventEndTime: null,
        setupTime: null,
        zendeskTicketNumber: null,
        isArchived: false,
        createdAt: baseDate,
        updatedAt: null,
      },
      {
        id: 102,
        calendarId: 201,
        buildingId: null,
        assigneeProfileId: null,
        ownerProfileId: null,
        scopeType: "business" as const,
        scopeId: 1,
        eventCode: "2222222",
        title: "Event B",
        description: null,
        location: null,
        isVirtual: false,
        isAllDay: false,
        startDatetime: baseDate,
        endDatetime: new Date("2026-03-28T14:00:00.000Z"),
        recurrenceRule: null,
        participantCount: null,
        technicianNeeded: false,
        requestCategory: null,
        equipmentNeeded: null,
        eventStartTime: null,
        eventEndTime: null,
        setupTime: null,
        zendeskTicketNumber: null,
        isArchived: false,
        createdAt: baseDate,
        updatedAt: null,
      },
    ],
    calendars: [
      {
        id: 201,
        userId: 301,
        name: "Main",
        color: "#000000",
        isPrimary: true,
        isArchived: false,
        scopeType: "business" as const,
        scopeId: 1,
        createdAt: baseDate,
        updatedAt: null,
      },
    ],
    buildings: [],
    profiles: [
      {
        id: 11,
        userId: null,
        firstName: "Joel",
        lastName: "Ying",
        email: "joel@example.com",
        phoneNumber: "5551112222",
        dateOfBirth: null,
        createdAt: baseDate,
        updatedAt: null,
      },
      {
        id: 22,
        userId: null,
        firstName: "Joel",
        lastName: "Ying",
        email: "joel@example.com",
        phoneNumber: "5553334444",
        dateOfBirth: null,
        createdAt: baseDate,
        updatedAt: null,
      },
    ],
    users: [],
  };

  const { workbook } = __hourLogExportTestUtils.buildWorkbook(data);
  assert.deepEqual(workbook.SheetNames, ["All Logs", "Joel Ying #11", "Joel Ying #22"]);
});
