#!/usr/bin/env node
const fs = require("node:fs");
const path = require("node:path");
const crypto = require("node:crypto");
const dotenv = require("dotenv");
const postgres = require("postgres");

const target = process.argv[2] === "prod" ? "prod" : "dev";
const envPath = path.resolve(process.cwd(), ".env");
dotenv.config({ path: envPath });

if (target === "prod") {
  if (!process.env.DATABASE_URL_PROD) {
    console.error("DATABASE_URL_PROD is not set in .env");
    process.exit(1);
  }
  process.env.CT3A_TARGET = "prod";
  process.env.DATABASE_URL = process.env.DATABASE_URL_PROD;
} else {
  process.env.CT3A_TARGET = "dev";
}

if (!process.env.DATABASE_URL) {
  console.error("DATABASE_URL is not set in .env");
  process.exit(1);
}

const dbUrl = process.env.DATABASE_URL;
const drizzleDir = path.resolve(process.cwd(), "drizzle");
const journalPath = path.resolve(drizzleDir, "meta", "_journal.json");
const skippedBootstrapFiles = new Set([
  // Legacy migration with invalid PostgreSQL syntax; superseded by 0023_event_building_backfill.sql.
  "0017_event_building.sql",
]);

function getMigrationFiles() {
  return fs
    .readdirSync(drizzleDir, { withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name.endsWith(".sql"))
    .map((entry) => entry.name)
    .filter((name) => !skippedBootstrapFiles.has(name))
    .sort((a, b) => a.localeCompare(b));
}

function getJournalEntries() {
  if (!fs.existsSync(journalPath)) return [];
  const raw = fs.readFileSync(journalPath, "utf8");
  const parsed = JSON.parse(raw);
  return Array.isArray(parsed.entries) ? parsed.entries : [];
}

function splitStatements(sqlText) {
  return sqlText
    .split("--> statement-breakpoint")
    .map((part) => part.trim())
    .filter(Boolean);
}

async function ensureDrizzleTable(sql) {
  await sql.unsafe('CREATE SCHEMA IF NOT EXISTS "drizzle";');
  await sql.unsafe(`
    CREATE TABLE IF NOT EXISTS "drizzle"."__drizzle_migrations" (
      "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      "hash" text NOT NULL,
      "created_at" bigint NOT NULL
    );
  `);
}

async function inspectState(sql) {
  const rows = await sql`
    select
      exists(
        select 1
        from information_schema.tables
        where table_schema = 'drizzle' and table_name = '__drizzle_migrations'
      ) as "hasMigrationTable",
      exists(
        select 1
        from information_schema.tables
        where table_schema = 'public' and table_name = 't3-app-template_business'
      ) as "hasBusinessTable",
      exists(
        select 1
        from information_schema.tables
        where table_schema = 'public' and table_name = 't3-app-template_user'
      ) as "hasUserTable",
      exists(
        select 1
        from information_schema.tables
        where table_schema = 'public' and table_name = 't3-app-template_calendar'
      ) as "hasCalendarTable",
      (
        select count(*)
        from information_schema.tables
        where table_schema = 'public' and table_name like 't3-app-template\_%' escape '\'
      )::int as "appTableCount"
  `;

  const state = rows[0] ?? {
    hasMigrationTable: false,
    hasBusinessTable: false,
    hasUserTable: false,
    hasCalendarTable: false,
    appTableCount: 0,
  };

  const hasSentinelTables =
    Boolean(state.hasBusinessTable) && Boolean(state.hasUserTable) && Boolean(state.hasCalendarTable);

  return {
    hasMigrationTable: Boolean(state.hasMigrationTable),
    hasSentinelTables,
    appTableCount: Number(state.appTableCount ?? 0),
  };
}

async function recordAllMigrationHashes(sql, files, journalByTag) {
  const existing = await sql`select hash from drizzle.__drizzle_migrations`;
  const existingHashes = new Set(existing.map((row) => row.hash));

  for (const fileName of files) {
    const filePath = path.join(drizzleDir, fileName);
    const sqlText = fs.readFileSync(filePath, "utf8");
    const hash = crypto.createHash("sha256").update(sqlText).digest("hex");
    if (existingHashes.has(hash)) continue;

    const tag = fileName.replace(/\.sql$/, "");
    const journalEntry = journalByTag.get(tag);
    const createdAt = Number(journalEntry?.when ?? Date.now());
    await sql`insert into drizzle.__drizzle_migrations ("hash", "created_at") values (${hash}, ${createdAt})`;
    existingHashes.add(hash);
  }
}

async function main() {
  const files = getMigrationFiles();
  const journalEntries = getJournalEntries();
  const journalByTag = new Map(journalEntries.map((entry) => [entry.tag, entry]));
  const sql = postgres(dbUrl, { max: 1 });

  try {
    const url = new URL(dbUrl);
    console.log(`Initializing ${target} database: ${url.hostname}:${url.port || "5432"}/${url.pathname.replace(/^\//, "")}`);

    const stateBefore = await inspectState(sql);
    await ensureDrizzleTable(sql);

    if (stateBefore.hasSentinelTables && !stateBefore.hasMigrationTable && stateBefore.appTableCount > 0) {
      console.log("Existing schema detected without migration history. Rebuilding drizzle.__drizzle_migrations only.");
      await recordAllMigrationHashes(sql, files, journalByTag);
      console.log("Database initialization completed.");
      return;
    }

    const existing = await sql`select hash from drizzle.__drizzle_migrations`;
    const existingHashes = new Set(existing.map((row) => row.hash));

    for (const fileName of files) {
      const filePath = path.join(drizzleDir, fileName);
      const sqlText = fs.readFileSync(filePath, "utf8");
      const hash = crypto.createHash("sha256").update(sqlText).digest("hex");
      if (existingHashes.has(hash)) {
        continue;
      }

      console.log(`Applying ${fileName}`);
      const statements = splitStatements(sqlText);
      for (const statement of statements) {
        await sql.unsafe(statement);
      }

      const tag = fileName.replace(/\.sql$/, "");
      const journalEntry = journalByTag.get(tag);
      const createdAt = Number(journalEntry?.when ?? Date.now());
      await sql`insert into drizzle.__drizzle_migrations ("hash", "created_at") values (${hash}, ${createdAt})`;
      existingHashes.add(hash);
    }

    console.log("Database initialization completed.");
  } finally {
    await sql.end();
  }
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
